[tool.poetry]
name = "rescuebox"
version = "0.1.0"
description = ""
authors = ["Jagath Jai Kumar <jagath.jaikumar@gmail.com>"]
packages = [{include = "rescuebox"}]

[tool.poetry.scripts]
rescuebox = "rescuebox.main:app"

[tool.poetry.dependencies]
requests = "^2.32.3"
python = ">=3.11,<3.13"
pyyaml = "^6.0.2"
typer = "^0.12.5"
llvmlite = "^0.44.0"
pytest = "^8.3.4"
httpx = "^0.28.1"
# add dependencies common to all plugins here
numpy = "2.1.0"
ollama = ">=0.4.7,<0.5.0"
pandas = ">=2.2.3,<3.0.0"
scikit_learn = ">=1.6.1,<2.0.0"
torch = ">=2.6.0,<3.0.0"
onnxruntime = "1.21.0"
opencv-python = ">=4.11.0.86,<5.0.0.0"
pypdf2 = ">=3.0.1,<4.0.0"
pdfplumber = ">=0.11.6"
fpdf = ">=1.7.2"

rb-lib = { path = "src/rb-lib", develop = true }

file-utils = { path = "src/file-utils", develop = true }
doc-parser = { path = "src/doc-parser", develop = true }
audio-transcription = { path = "src/audio-transcription", develop = true }
age-and-gender-detection = { path = "src/age_and_gender_detection", develop = true }
text-summary = {path = "src/text-summary", develop = true}
message-analyser = {path = "src/message-analyser", develop = true}

# Don't add new packages here, add them appropriately in the list above
beautifulsoup4 = "^4.13.3"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
isort = "^5.13.2"
pytest = "^8.3.3"
ruff = "^0.7.1"
pre-commit = "^4.0.1"

[tool.poetry.group.api.dependencies]
rb-api = { path = "src/rb-api", develop = true }

[tool.poetry.group.bundling.dependencies]
pyinstaller = "^5.13.2"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
